# Generated by Django 4.0.3 on 2022-05-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longURL', models.CharField(max_length=255)),
                ('shortURL', models.CharField(max_length=255)),
            ],
        ),
    ]
